export const buildingList = [
    {name: "national-epic", radio: 1},
    {name: "heroic-epic", radio: 1},
    {name: "great-library", radio: 1},
    {name: "oxford-university", radio: 1},
    {name: "globe-theatre", radio: 1},
    {name: "palace", radio: 1},
    {name: "parthenon", radio: 1},
    {name: "sistine-chapel", radio: 1},
    {name: "uffizi", radio: 1},
    {name: "hermitage", radio: 1},
    {name: "louvre", radio: 1},
    {name: "broadway", radio: 1},
    {name: "sydney-opera-house", radio: 1},
    {name: "royal-library", radio: 1},
    {name: "amphitheater", radio: 0},
    {name: "cathedral", radio: 0},
    {name: "museum", radio: 0},
    {name: "opera-house/ceilidh-hall", radio: 0},
    {name: "broadcast-tower", radio: 0},
    {name: "hotel", radio: 0},
    {name: "airport", radio: 0},
    {name: "national-visitor-center", radio: 0}
];