export const civList = [
    "american",
    "arabian",
    "assyrian",
    "austrian",
    "aztec",
    "babylonian",
    "brazilian",
    "byzantine",
    "carthaginian",
    "celtic",
    "chinese",
    "danish",
    "dutch",
    "egyptian",
    "english",
    "ethiopian",
    "french",
    "german",
    "greek",
    "hunnic",
    "incan",
    "indian",
    "indonesian",
    "iroquois",
    "japanese",
    "korean",
    "mayan",
    "mongolian",
    "moroccan",
    "ottoman",
    "persian",
    "polish",
    "polynesian",
    "portuguese",
    "roman",
    "russian",
    "shoshone",
    "siamese",
    "songhai",
    "spanish",
    "swedish",
    "venetian",
    "zulu"
];

export const buildingList = [
    {name: "national-epic", radio: 1, type: "writing", slots: 1, multiplierBonus: 0},
    {name: "heroic-epic", radio: 1, type: "writing", slots: 1, multiplierBonus: 0},
    {name: "great-library", radio: 1, type: "writing", slots: 2, multiplierBonus: 0},
    {name: "oxford-university", radio: 1, type: "writing", slots: 2, multiplierBonus: 0},
    {name: "globe-theatre", radio: 1, type: "writing", slots: 2, multiplierBonus: 0},
    {name: "palace", radio: 1,  type: "art", slots: 1, multiplierBonus: 0},
    {name: "parthenon", radio: 1, type: "art", slots: 1, multiplierBonus: 0},
    {name: "sistine-chapel", radio: 1, type: "art", slots: 2, multiplierBonus: 0},
    {name: "uffizi", radio: 1, type: "art", slots: 3, multiplierBonus: 0},
    {name: "hermitage", radio: 1, type: "art", slots: 3, multiplierBonus: 0},
    {name: "louvre", radio: 1, type: "art", slots: 4, multiplierBonus: 0},
    {name: "broadway", radio: 1, type:"music", slots: 3, multiplierBonus: 0},
    {name: "sydney-opera-house", radio: 1, type: "music", slots: 2, multiplierBonus: 0},
    {name: "royal-library", radio: 1, type: "writing", slots: 1, multiplierBonus: 0},
    {name: "amphitheater", radio: 0, type: "writing", slots: 1, multiplierBonus: 0},
    {name: "cathedral", radio: 0, type: "art", slots: 1, multiplierBonus: 0},
    {name: "museum", radio: 0, type: "art", slots: 2, multiplierBonus: 0},
    {name: "opera-house/ceilidh-hall", radio: 0, type: "music", slots: 1, multiplierBonus: 0},
    {name: "broadcast-tower", radio: 0, type: "music", slots: 1, multiplierBonus: 0},
    {name: "hotel", radio: 0, type: "multiplier", slots: 0, multiplierBonus: 0.5},
    {name: "airport", radio: 0, type: "multiplier", slots: 0, multiplierBonus: 0.5},
    {name: "national-visitor-center", radio: 0, type: "multiplier", slots: 0, multiplierBonus: 1}
];

export const greatWorkTypeList = [
    "writing",
    "art",
    "music",
    "artifact"
];

export const eraList = [
    "ancient",
    "classical",
    "medieval",
    "renaissance",
    "industrial",
    "modern",
    "atomic",
    "information"
];